---
- name: Import pre-checks
  ansible.builtin.import_tasks: pre-checks.yml

- name: ECS Anywhere | Download ECS Anywhere Install Script
  ansible.builtin.get_url:
    url: "{{ ecs_anywhere_aws_script_url }}"
    dest: /tmp
    mode: '0550'
  become: true

- name: ECS Anywhere | Create SSM Activation Code
  delegate_to: localhost
  ansible.builtin.shell:
    cmd: >
      gaggle_net.ecs_anywhere.aws_ssm_activation
      state=create
      iam_role="{{ ecs_anywhere_iam_role }}"
      region="{{ ecs_anywhere_aws_region }}"
  environment:
    AWS_PROFILE: "{{ ecs_anywhere_aws_sso_profile | default(omit) }}"
  register: ssm_activation_info
  become: "{{ ecs_anywhere_use_sudo_for_local_tasks }}"
  changed_when: >-
    ssm_activation_info.activation_id is defined and
    ssm_activation_info.activation_code is defined

- name: Set SSM Activation Fact
  ansible.builtin.set_fact:
    ssm_activation_id: "{{ ssm_activation_info.activation_id }}"
    ssm_activation_code: "{{ ssm_activation_info.activation_code }}"

- name: ECS Anywhere | Run ECS Anywhere Install Script and Register SSM Agent
  ansible.builtin.shell:
    cmd: >
      /tmp/ecs-anywhere-install-latest.sh --region "{{ ecs_anywhere_aws_region }}" --cluster "{{ ecs_anywhere_aws_ecs_cluster }}"
      --activation-id "{{ ssm_activation_id }}" --activation-code "{{ ssm_activation_code }}"
      {{ '--docker-install-source none' if ecs_anywhere_include_docker_role else '' }}
  become: true
  register: ecs_registration
  changed_when: ecs_registration.rc == 0
