---
- import_tasks: pre-checks.yml

- import_tasks: check-cluster-exists.yml

- name: Create ecs directory
  file:
    path: "{{ aws_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0611
  become: yes

- name: Download ECS Anywhere Install Script
  get_url: 
    url: https://amazon-ecs-agent-packages-preview.s3.us-east-1.amazonaws.com/ecs-anywhere-install.sh
    dest: "{{ aws_dir }}"
    mode: '0550'
    checksum: sha256:https://amazon-ecs-agent-packages-preview.s3.us-east-1.amazonaws.com/ecs-anywhere-install.sh.sha256
  become: yes

- name: create ssm activation code
  local_action: ansible.builtin.command /usr/bin/aws ssm create-activation --iam-role {{ ssm_role }} --registration-limit {{ ansible_play_hosts | length }} --profile {{ aws_profile }}
  register: ssm_activation_info
  run_once: true
  become: false

- set_fact:
    ssm_activation_id: "{{ (ssm_activation_info.stdout | from_json) | json_query('\"ActivationId\"') }}"
    ssm_activation_code: "{{ (ssm_activation_info.stdout | from_json) | json_query('\"ActivationCode\"') }}"
    

- name: Run ECS Anywhere Install Script and Register SSM Agent
  shell:
    '"{{ aws_dir }}"/ecs-anywhere-install.sh --region "{{ aws_region }}" --cluster "{{ ecs_cluster }}" --activation-id "{{ ssm_activation_id }}" --activation-code "{{ ssm_activation_code }}" >> "{{ aws_dir }}"/ecs-anywhere-install.log'
  become: yes
  register: ecs_registration
...
