---
- name: ECS Anywhere | Get SSM Instance Info
  shell: ssm-cli get-instance-information
  register: ssm_instance_info
  become: yes

- set_fact:
    ssm_id: "{{ (ssm_instance_info.stdout | from_json) | json_query('\"instance-id\"') }}"


- name: ECS Anywhere | Deregister SSM Instance
  local_action:
    module: gaggle_net.ecs_anywhere.aws_ssm_instance
    state: deregister
    instance_id: "{{ ssm_id }}"
    region: us-west-2

- name: ECS Anywhere | Delete Local Registration Info
  file:
    path: /var/lib/amazon/ssm/registration
    state: absent
  become: yes

- name: ECS Anywhere | Delete ECS Agent Data
  file:
    path: /var/lib/ecs/data/agent.db
    state: absent
  become: yes

- name: ECS Anywhere | Stop the SSM Agent Service
  systemd:
    name: amazon-ssm-agent.service
    state: stopped
  become: yes

- name: ECS Anywhere | Stop the ECS Agent Service
  systemd:
    name: ecs.service
    state: stopped
  become: yes

- name: ECS Anywhere | Install python3-docker
  yum:
    name: python3-docker
    state: installed
  become: yes

- name: ECS Anywhere | Get List of All Running Docker Containers
  docker_host_info:
    containers: true
  register: docker_info
  become: yes

- name: ECS Anywhere | Remove All Docker Containers
  docker_container:
    name: '{{ item.Names[0] | regex_replace("^/", "") }}'
    state: absent
  loop: "{{ docker_info.containers }}"
  become: yes
