---
- name: ECS Anywhere | Check If Using cgroups V2
  stat:
    path: /sys/fs/cgroup/cgroup.controllers
  register: cgroup_controllers
 
- name: ECS Anywhere | Fail If Using cgroups V2
  fail:
    msg: Your system is using cgroups v2, which is not supported by ECS
  when: cgroup_controllers.stat.exists
