---
- name: ECS Anywhere | Check If Using cgroups V2
  stat:
    path: /sys/fs/cgroup/cgroup.controllers
  register: cgroup_controllers
 
- name: ECS Anywhere | Fail If Using cgroups V2
  fail:
    msg: Your system is using cgroups v2, which is not supported by ECS
  when: cgroup_controllers.stat.exists

- name: ECS Anywhere | Check Authentication to AWS
  local_action: ansible.builtin.command /usr/bin/aws sts get-caller-identity --profile {{ aws_profile }}
  register: aws_auth
  ignore_errors: yes

- name: ECS Anywhere | Stop on Login Failure
  fail:
    msg: Failed to authenticate to AWS. Check credentials and try again.
  when: aws_auth != 0
