---
- name: ECS Anywhere | Stop the SSM Agent Service
  systemd:
    name: amazon-ssm-agent.service
    state: stopped
 
- name: ECS Anywhere | Stop the ECS Service
  systemd:
    name: ecs.service
    state: stopped

- name: ECS Anywhere | Delete ECS Agent Data
  file:
    path: /var/lib/ecs/data/agent.db
    state: absent

- name: ECS Anywhere | Create SSM Activation Code
  local_action:
    module: gagglenet.ecs_anywhere.aws_ssm_activation
  register: ssm_activation_info

- set_fact:
    ssm_activation_id: "{{ (ssm_activation_info.ActivationId }}"
    ssm_activation_code: "{{ (ssm_activation_info.ActivationCode }}"

- name: ECS Anywhere | Set the ECS Cluster Name
  lineinfile:
    state: present
    path: /etc/ecs/ecs.config
    regexp: '^[# ]*ECS_CLUSTER\s*=\s*'
    line: ECS_CLUSTER={{ aws_ecs_cluster }}
 
- name: ECS Anywhere | Register the SSM Agent
  shell:
    "/usr/bin/amazon-ssm-agent -register -y -code {{ ssm_activation_code }} -id {{ ssm_activation_id }} -region {{ aws_region }}"

- name: ECS Anywhere | Start the Amazon SSM Agent Service 
  systemd:
    name: amazon-ssm-agent.service
    state: started

- name: ECS Anywhere | Start the ECS Service
  systemd:
    name: ecs.service
    state: started     
