---
- name: Deregister SSM Instance in AWS ECS
  hosts: aws_ecs
  vars:
    aws_region: us-west-2
    aws_ecs_cluster: ecs-anywhere
    iam_role: ecsAnywhereRole
  tasks:
    - name: Include role for deregistering SSM instance
      ansible.builtin.include_role:
        name: gaggle_net.ecs_anywhere.ecs_anywhere
        tasks_from: deregister-ssm-instance
