---
- hosts: aws_ecs
  tasks:
    - import_role:
        name: gaggle_net.ecs_anywhere.ecs_anywhere
  become: yes
  vars:
    aws_region: us-west-2
    aws_ecs_cluster: ecs-anywhere
    iam_role: ecsAnywhereRole
 
