---
- name: Register ECS Anywhere Instance
  hosts: aws_ecs
  gather_facts: false
  become: true
  tasks:
    - name: Include ECS Anywhere Role
      ansible.builtin.include_role:
        name: gaggle_net.ecs_anywhere.ecs_anywhere
        tasks_from: register-ssm-instance
